### ISSUE TITLE
config secret = "true" support (create encrypted secret on fs)

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#122]
![FlowDiagramForSecrets_CR-Page-1.jpg](https://images.zenhubusercontent.com/5e29b757c11572c474c47aa5/520e814d-5849-4361-b9d7-88cd004ab26a)

**Comment by ashwathishiva** [comment]
`qliksense config set-secrets qliksense.mongoDbUri="mongo://mongo:3307" --secret=true` will work.

Here are some things that need a mention:
- the format: `servicename[name=key]="value"` is now outdated. configs can now be specified in the format: `servicename.key="value"` 
- a secret key pair will be generated once for the context that this command is invoked under
- secret key-pair will be stored in: `~/.qliksense/secrets/contexts/<context-name>/secrets`
- value is encrypted and stored as part of a K8s secret with: <servicename>.yaml in: `~/.qliksense/contexts/<context-name>/secrets/<servicename>.yaml`
- update CR with the secret details.
- When CR is viewed using qliksense config view secret resource is displayed along with CR

Example:
Secret resource: `qliksense.yaml`:
```
apiVersion: v1
data:
  mongoDbUri: <base64encoded value>
kind: Secret
metadata:
  name: ashqliksense-qliksense-sense_installer
type: Opaque
```
The CR:
```
apiVersion: qlik.com/v1
kind: Qliksense
metadata:
  name: contextname
spec:
  profile: docker-desktop
  secrets:
    qliksense:
    - name: mongoDbUri
      valueFrom:
        secretKeyRef:
          name: contextname-qliksense-sense_installer
          key: mongoDbUri
    - name: testKey0
      value: <base64-encoded value>
    testSvcName:
    - name: testKey1
      valueFrom:
        secretKeyRef:
          name: contextname-testSvcName-sense_installer
          key: testKey1
  configs:
    qliksense:
    - name: acceptEULA
      value: "yes"
  rotateKeys: "yes"
  storageClassName: test-sc
  namespace: test-ns
  git:
    repository: https://github.com/my-org/qliksense-k8s
  releaseName: contextname
```
