### ISSUE TITLE
Add support to specify manifestsRoot as part of config

### ISSUE THREAD

**Issue by ashwathishiva** [qlik-oss/sense-installer#128]
We should be able to set manifestsRoot through the config command.

qliksense config set manifestsRoot=<path>

Resulting CR will look like:
```
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
  labels:
    version: v1.0.0
spec:
  git:
    repository: https://github.com/my-org/qliksense-k8s
  profile: manifests/docker-desktop
  **manifestsRoot: /Usr/ddd/my-k8-repo/manifests**
  namespace: myqliksense
  storageClassName: efs
```
