### ISSUE TITLE
CI and instructions for  kubectl plugin

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#132]
- provide a script available via a url for curl (and iwr on windows) that downloads and installs the qliksense as a kubectl plugin. script could be stored in artifactory see for example: https://kots.io/kots-cli/getting-started/
- optionally provide krew compatible plugin

**Comment by ibiqlik** [comment]
WIP https://github.com/qlik-oss/sense-installer/pull/209

**Comment by ibiqlik** [comment]
I'm starting to question if the convenience scripts vs few cmd lines documented are needed?

For example:
Documentation
```
curl -Lo qliksense https://github.com/qlik-oss/sense-installer/releases/download/v0.7.0/qliksense-linux-amd64
chmod +x qliksense
sudo mv qliksense /usr/local/bin
```
vs Script:
```
curl -Lo get-qliksense-cli.sh https://github.com/qlik-oss/sense-installer/releases/download/v0.7.0/install.sh
sh get-qliksense-cli.sh
```

The scripts will make sense if there will be multiple extra steps that normally a user should not be bothered !

**Comment by bkuschel** [comment]
I was thinking more along the lines of:

`curl https://qlik.com/install | bash`
`kubectl qliksense help`

Not super critical though the krew part is something we should prepare for (create the krew manifest and tar ball)

**Comment by bkuschel** [comment]
` kubectl krew install --manifest=path/to/qliksense.yaml --archive=path/to/qliksense-windows-amd64.tar.gz`

qliksense.yaml
```yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: qliksense
spec:
  version: "v0.6.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/qlik-oss/sense-installer/releases/download/v0.6.0/qliksense-linux-amd64.tar.gz
    sha256: "9de0a5985df519381bccc07e09c6f4af0b38e9c857bcf5d4cbfdce9242440881"
    bin: qliksense-linux-amd64
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/qlik-oss/sense-installer/releases/download/v0.6.0/qliksense-darwin-amd64.tar.gz
    sha256: "f0817b245100623a6b6f126381111fd62e003b70b7c26e10b020402d8c918bfb"
    bin: qliksense-darwin-amd64
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/qlik-oss/sense-installer/releases/download/v0.6.0/qliksense-windows-amd64.tar.gz
    sha256: "186377c0fec31014424c8178ea0f985527b351c1fcb4001a8ee84c031c113331"
    bin: qliksense-windows-amd64.exe
  shortDescription: installer for the qliksense application
  homepage: https://github.com/qlik-oss/sense-installer
  description: |
    qliksense cli tool provides a wrapper around the porter api as well as
                    provides addition functionality
    Usage:
      kubectl qliksense [command]
​
    Available Commands:
      about       About Qlik Sense
      config      do operations on/around CR
      fetch       fetch a release from qliksense-k8s repo
      help        Help about any command
      install     install a qliksense release
      operator    Configuration for operator
      pull        Pull docke images for offline install
      version     Print the version number of qliksense cli
​
    Flags:
      -h, --help   help for qliksense
​
    Use "kubectl qliksense [command] --help" for more information about a command.
```

You will need to change the checksum.

Eventually ...
https://krew.sigs.k8s.io/docs/developer-guide/release/new-plugin/
