### ISSUE TITLE
Support gitops configs as part of `qliksense config set` in CLI

### ISSUE THREAD

**Issue by ashwathishiva** [qlik-oss/sense-installer#194]
We will want to support gitops configs like below as part of the `set` command:
```
gitOps:
    enabled: "yes"
    schedule: "*/10 * * * *"
    watchBranch: master
    image: busybox
```

In the end, CR should include the above section if it has been configured.
