### ISSUE TITLE
Handle configuration and string values with quotations

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#254]
qliksense config set-secrets identity-providers.idpConfigs='[ { \"realm\": \"QSEoK\" }]'

For PowerShell related kubectl issue:
https://stackoverflow.com/questions/55602559/kubectl-patch-works-on-linux-bash-but-not-in-windows-powershell-ise

**Comment by ffoysal** [comment]
`qliksense config set-configs identity-providers.idpConfigs='[ { \"realm\": \"QSEoK\" }]'` looks in the CR
like this 
```
spec:
  configs:
    identity-providers:
    - name: idpConfigs
      value: '[ { \"realm\": \"QSEoK\" }]'
```

and 
`qliksense config set-configs identity-providers.idpConfigs='[ { "realm": "QSEoK" }]'`
look like this in CR

```
spec:
  configs:
    identity-providers:
    - name: idpConfigs
      value: '[ { "realm": "QSEoK" }]'
```
looks the issue is fixed now.
