### ISSUE TITLE
Provide imperative configuration through CLI-2

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#32]
Allow usage of CLI to add new qliksense application secrets and set properties. Should be somewhat aligned with the way kubectl config works. 

```shell
> kubectl qliksense config set-secrets qliksense[name=mongoDbUri]="mongo://mongo:3307" --secret=false
> kubeclt qliksense config set-secrets qliksense[name=messagingPassword]="abc123"  --secret=true
> kubectl qliksense config view
> kubectl qliksense config list-contexts
```
```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
spec:
  git:
    repository: https://github.com/my-org/qliksense-k8s
  profile: manifests/docker-desktop
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
    - name: messagingPassword
      valueFromKey: messagingPassword
```

CLI should store configuration as:

~/.qliksense/myqliksense.yaml
```yaml
apiVersion: qlik.com/v1  
kind: QlikSense
metadata:
  name: myqliksense
  labels:
    version: v1.0.0
spec:
  profile: manifests/docker-desktop
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
    - name: messagingPassword
      valueFromKey: messagingPassword
---
apiVersion: v1
kind: Secret
  name: myqliksense
type: Opaque
data:
  messagingPassword: YWJjMTIz
```
~/.qliksense/myotherqliksense.yaml
```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myotherqliksense
  labels:
    version: v2.0.0
spec:
  gitRepo: https://github.com/myorg/qliksense-k8s
  profile: manifests/docker-desktop
  namespace: myotherqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://atlasmongo:3307"
```

**Comment by ashwathishiva** [comment]
I have finished working on the following commands:
>qliksense config set-context myqliksense
> qliksense config set profile=docker-desktop
> qliksense config set namespace=qliksense
> qliksense config set storageClassName=efs
> qliksense config set git.repository="https://github.com/my-org/qliksense-k8s"  # Uses kubernetes operator when specified
> qliksense config set-configs qliksense[name=acceptEULA]="yes"
> qliksense config view

Functional code until this point. 
I have `set-secrets` working the same way as `set-configs` at this point. I'm aware that secrets will work differently, I'm working with Foysal on this.

I'm currently working on cleaning up some code, I intend to create a PR with the above changes. Will work on secrets and tests right after these.

**Comment by ashwathishiva** [comment]
Setting `secret` to `false` in the command below:
`qliksense config set-secrets attribute0[name=Key0]="Value0" --secret=false`

This will encrypt the secret value and display the encrypted value as is, in the secrets section of the CR.

For example, the above command will yield the resulting CR:
```
apiVersion: qlik.com/v1
kind: Qliksense
metadata:
  name: myqliksense
spec:
  profile: docker-desktop
  secrets:
    attribute0:
    - name: Key0
      value: !!binary |
        <base64-encode(encrypted secret value)>
  rotateKeys: "yes"
  storageClassName: my-ns
  namespace: my-ns
  releaseName: myqliksense 
```
