### ISSUE TITLE
Qlik Sense cr generation using imperative/declarative methods

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#38]
# Summary
- Remove porter as dependency of CLI (retain functionality/actions)
- Implement imperative configuration
- Convert pull/push to skopeo

## CLI Installation
```shell
> kubectl krew install qliksense # Installation of the qliksense plugin for kubectl
```
## Option 1: Install with no git repo specified in configuration specification
Manifest is rendered by the CLI an applied  ex:
```shell
> kubectl qliksense config set-context myqliksense
> kubectl qliksense config set profile=docker-desktop
> kubectl qliksense config set namespace=qliksense
> kubectl qliksense config set storageClassName=efs
> kubectl qliksense config set-configs qliksense[name=acceptEULA]="yes"
> kubectl qliksense config set-secrets qliksense[name=mongoDbUri]="mongo://mongo:3307" --secret=false
> kubectl qliksense config set-secrets qliksense[name=messagingPassword]=abc123
> kubectl qliksense config view
```
```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
spec:
  profile: manifests/docker-desktop
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
    - name: messagingPassword
      valueFromKey: messagingPassword
```
```shell
> kubectl qliksense config install 1.0.0
  → kubectl qliksense fetch 1.0.0 # pull down qliksense-k8s@1.0.0
  → kubectl qliksense operator view | kubectl apply -f # operator manifest (CRD)
  → kubeclt qliksense config apply | kubectl apply -f # generates patches (if required) in configuration directory, applies manifest
  → kubectl qliksense config view | kubectl apply -f # generates Custom Resource manifest (CR)
```
### Air-Gap Operation
Images are pull/pushed when dockerRegistry attribute is supplied, ex. 
```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
  labels:
    version: 1.0.0
spec:
  profile: manifests/docker-desktop
  namespace: myqliksense
  dockerRegistry: myregistry:4040
```
```shell
> kubectl qliksense config install 1.0.0
  → kubectl qliksense fetch 1.0.0 # pull down qliksense-k8s@1.0.0 git repo
  → kubectl qliksense save-images 1.0.0 # pull down qliksense-k8s@1.0.0 images
  → kubectl qliksense operator view | kubectl apply -f # operator manifest (CRD)
  → kubeclt qliksense config load-images
  → kubeclt qliksense config apply | kubectl apply -f # generates patches (if required) in configuration directory, applies manifest
  → kubectl qliksense config view | kubectl apply -f # generates Custom Resource manifest (CR)
```
## CLI configuration repository (local file system)
~/.qliksense/myqliksense.yaml

```yaml
apiVersion: qlik.com/v1  
kind: QlikSense
metadata:
  name: myqliksense
  labels:
    version: v1.0.0
spec:
  profile: manifests/docker-desktop
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
    - name: messagingPassword
      valueFromKey: messagingPassword
---
apiVersion: v1
kind: Secret
name: myqliksense
type: Opaque
data:
  messagingPassword: YWJjMTIz
```

~/.qliksense/myotherqliksense.yaml
```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myotherqliksense
  labels:
    version: v2.0.0
spec:
  gitRepo: https://github.com/myorg/qliksense-k8s
  profile: manifests/docker-desktop
  namespace: myotherqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://atlasmongo:3307"
```
