### ISSUE TITLE
Qlik Sense CLI driven manifests generation and installation

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#39]
# Summary
- Install CRD using CLI (`kubectl qliksense operator view | kubectl apply -f`)
- Install Qliksense without git fork repo (`kubectl qliksense config install 1.0.0`)

# Install Qliksense With Git Repo

using `qliksense`(developed at #38 ) commands generate this
```
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
spec:
  profile: manifests/docker-desktop
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
    - name: messagingPassword
      valueFromKey: messagingPassword
```
At the `kubectl qliksense install v1.0.0`
CLI will fetch and install CRD, qliksense config, CR.
The CR will associate the installed resources with the operator. So that bare minimum operator can delete  the resources and latter on if the customer switch to git mode, operator can easily switch the installation without service impact.
