### ISSUE TITLE
overhauling key rotation

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/sense-installer#425]
```yaml
apiVersion: qlik.com/v1
kind: Qliksense
metadata:
  labels:
    version: qliksense-v1.58.2
  name: mokul
spec:
  storageClassName: nf-client
  profile: somepath
```
## k-apis repo
- use previously generated keys if exist in the cluster
- generate new keys if not exist in the cluster

need extra param in the k-api method to have None functionality

need to change installer code to not have rotateKeys in the default CR anymore

to rotate the keys
`qliksense keys rotate` 
 - will delete the secrete from the cluster

list of repos:
- qliksense-opeartor (kuz server)
- sense-installer
