### ISSUE TITLE
Provide imperative configuration through CLI-1

### ISSUE THREAD

**Issue by ashwathishiva** [qlik-oss/sense-installer#72]
Allow usage of CLI to create new qliksense application configuration instances and set properties. Should be somewhat aligned with the way kubectl config works. 

```shell
> kubectl qliksense config set-context myqliksense
> kubectl qliksense config set profile=docker-desktop
> kubectl qliksense config set namespace=qliksense
> kubectl qliksense config set storageClassName=efs
> kubectl qliksense config set rotateKeys=yes
> kubectl qliksense config set git.repository="https://github.com/my-org/qliksense-k8s"  # Uses kubernetes operator when specified
> kubectl qliksense config set-configs qliksense[name=acceptEULA]="yes"

> kubectl qliksense config set profile=docker-desktop namespace=qliksense storageClassName=qliksense rotateKeys=yes
```
```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
spec:
  git:
    repository: https://github.com/my-org/qliksense-k8s
  profile: manifests/docker-desktop
  namespace: myqliksense
  storageClassName: efs
  rotateKeys: "no"
  releaseName: myqliksense
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
```

CLI should store configuration as: `~/.qliksense/contexts/myqliksense/myqliksense.yaml`
```yaml
apiVersion: qlik.com/v1  
kind: QlikSense
metadata:
  name: myqliksense
  labels:
    version: v1.0.0
spec:
  profile: manifests/docker-desktop
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"

~/.qliksense/contexts/myotherqliksense/myotherqliksense.yaml

```yaml
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myotherqliksense
  labels:
    version: v2.0.0
spec:
  gitRepo: https://github.com/myorg/qliksense-k8s
  profile: manifests/docker-desktop
  namespace: myotherqliksense
  storageClassName: efs
  rotateKeys: "yes"
  releaseName: myotherqliksense
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://atlasmongo:3307"
```
All context info is stored in: `~/.qliksense/config.yaml`:
```yaml
apiVersion: config.qlik.com/v1
kind: QliksenseConfig
metadata:
  name: QliksenseConfigMetadata
spec:
  contexts:
  - name: qlik-default
    crFile: /Users/fki/.qliksense/contexts/qlik-default/qlik-default.yaml
  - name: myqliksense
    crFile: /Users/fki/.qliksense/contexts/myqliksense/myqliksense.yaml
  currentContext: qliksense-default
```
