### ISSUE TITLE
Qliksense kubernetes operator for git fork

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/sense-installer#74]
# Summary
- Install CRD using CLI (`kubectl qliksense operator view | kubectl apply -f`)
- Install Qliksense with git fork repo (`kubectl qliksense config install 1.0.0`)

# Install Qliksense With Git Repo

using `qliksense`(developed at #38 ) commands generate this
```
apiVersion: qlik.com/v1
kind: QlikSense
metadata:
  name: myqliksense
spec:
  profile: manifests/docker-desktop
  git:
    repository: https://github.com/qlik-oss/example-fork?ref=v0.0.1
  namespace: myqliksense
  storageClassName: efs
  configs:
  - qliksense:
    - name: acceptEULA
      value: "yes"
  secrets:
  - qliksense:
    - name: mongoDbUri
      value: "mongo://mongo:3307"
    - name: messagingPassword
      valueFromKey: messagingPassword
```
```shell
> kubectl qliksense config install 1.0.0
       -> kubectl qliksense config view | kubectl apply -f # generates Custom Resource manifest (CR)
```

## Qliksense Kubernetes Operator
After applying the CR, operator will 
- fetch config from git repo 
- create patches
- run `kustomize build` to generate manifest
- create all those resources from generated manifest in the cluster
- optionally make the PR to the git repo
