### ISSUE TITLE
Encrypt secret information on disk

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#85]
When we store secret information on disk as part of the CR definition (in totality) it should be encrypted using a strong cipher.

We use RSA keys of length 4096 bits to encrypt secrets using PKCS1v15 padding. (We can change the algorithm if necessary)

Setting `secret` to `false` in the command below:
`qliksense config set-secrets attribute0[name=Key0]="Value0" --secret=false`

This will encrypt the secret value and display the encrypted value as is, in the `secrets` section of the CR.

For example, the above command will yield the resulting CR:
```
apiVersion: qlik.com/v1
kind: Qliksense
metadata:
  name: myqliksense
spec:
  profile: docker-desktop
  secrets:
    attribute0:
    - name: Key0
      value: !!binary |
        <base64-encode(encrypted secret value)>
  rotateKeys: "yes"
  storageClassName: my-ns
  namespace: my-ns
  releaseName: myqliksense 
```
